# Generated by Django 4.2.1 on 2023-07-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='AncientTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.JSONField(blank=True, default=list, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('damage', models.CharField(blank=True, max_length=100, null=True)),
                ('converted_energy_cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('converted_retreat_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('evolves_from', models.CharField(blank=True, max_length=100, null=True)),
                ('evolves_to', models.JSONField(blank=True, default=list, null=True)),
                ('flavor_text', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.CharField(blank=True, max_length=100, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('regulation_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_pokedex_numbers', models.JSONField(blank=True, default=list, null=True)),
                ('number', models.CharField(blank=True, max_length=3, null=True)),
                ('rarity', models.CharField(blank=True, max_length=100, null=True)),
                ('retreat_cost', models.JSONField(blank=True, default=list, null=True)),
                ('rules', models.JSONField(blank=True, default=list, null=True)),
                ('subtypes', models.JSONField(blank=True, default=list, null=True)),
                ('supertype', models.CharField(blank=True, choices=[('pokemon', 'Pokemon'), ('trainer', 'Trainer'), ('energy', 'Energy')], max_length=100, null=True)),
                ('types', models.JSONField(blank=True, default=list, null=True)),
                ('in_collection', models.BooleanField(default=False)),
                ('abilities', models.ManyToManyField(blank=True, related_name='cards_abilities', to='main.abilities')),
                ('ancient_trait', models.ManyToManyField(blank=True, related_name='cards_ancient_trait', to='main.ancienttrait')),
                ('attacks', models.ManyToManyField(blank=True, related_name='cards_attacks', to='main.attacks')),
            ],
        ),
        migrations.CreateModel(
            name='CardMarketPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.CharField(blank=True, max_length=100, null=True)),
                ('large_img', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, choices=[('legal', 'Legal'), ('banned', 'Banned')], default='legal', max_length=100, null=True)),
                ('expanded', models.CharField(blank=True, choices=[('legal', 'Legal'), ('banned', 'Banned')], default='legal', max_length=100, null=True)),
                ('unlimited', models.CharField(blank=True, choices=[('legal', 'Legal'), ('banned', 'Banned')], default='legal', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('colorless', 'Colorless'), ('darkness', 'Darkness'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('fire', 'Fire'), ('grass', 'Grass'), ('lightning', 'Lightning'), ('metal', 'Metal'), ('psychic', 'Psychic'), ('water', 'Water')], max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TcgplayerPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_market', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reverse_holo_market', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weaknesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('colorless', 'Colorless'), ('darkness', 'Darkness'), ('dragon', 'Dragon'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('fire', 'Fire'), ('grass', 'Grass'), ('lightning', 'Lightning'), ('metal', 'Metal'), ('psychic', 'Psychic'), ('water', 'Water')], max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tcgplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('prices', models.ManyToManyField(blank=True, related_name='tcgplayer_prices', to='main.tcgplayerprices')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cards', models.ManyToManyField(to='main.card')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('printed_total', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('ptcgo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('release_data', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='cardsets_images', to='main.images')),
                ('legalities', models.ManyToManyField(blank=True, related_name='cardsets_legalities', to='main.legalities')),
            ],
        ),
        migrations.CreateModel(
            name='CardMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('prices', models.ManyToManyField(blank=True, related_name='cardmarket_prices', to='main.cardmarketprices')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ManyToManyField(blank=True, related_name='cards_card_set', to='main.cardset'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardmarket',
            field=models.ManyToManyField(blank=True, related_name='cards_cardmarket', to='main.cardmarket'),
        ),
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='cards_images', to='main.images'),
        ),
        migrations.AddField(
            model_name='card',
            name='legalities',
            field=models.ManyToManyField(blank=True, related_name='cards_legalities', to='main.legalities'),
        ),
        migrations.AddField(
            model_name='card',
            name='resistances',
            field=models.ManyToManyField(blank=True, related_name='cards_resistances', to='main.resistances'),
        ),
        migrations.AddField(
            model_name='card',
            name='tcgplayer',
            field=models.ManyToManyField(blank=True, related_name='cards_tcgplayer', to='main.tcgplayer'),
        ),
        migrations.AddField(
            model_name='card',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='cards_weaknesses', to='main.weaknesses'),
        ),
    ]
