# Generated by Django 4.2.1 on 2023-07-07 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('supertype', models.CharField(blank=True, max_length=100)),
                ('subtypes', models.JSONField()),
                ('level', models.CharField(blank=True, max_length=100)),
                ('hp', models.CharField(blank=True, max_length=100)),
                ('types', models.JSONField()),
                ('evolves_from', models.CharField(blank=True, max_length=100)),
                ('evolves_to', models.JSONField()),
                ('rules', models.JSONField()),
                ('ancient_trait_name', models.CharField(blank=True, max_length=100)),
                ('ancient_trait_text', models.CharField(blank=True, max_length=100)),
                ('abilities', models.JSONField()),
                ('attacks', models.JSONField()),
                ('weaknesses', models.JSONField()),
                ('resistances', models.JSONField()),
                ('retreat_cost', models.JSONField()),
                ('converted_retreat_cost', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('rarity', models.CharField(blank=True, max_length=100)),
                ('flavor_text', models.TextField(blank=True)),
                ('national_pokedex_numbers', models.JSONField()),
                ('unlimited_legality', models.CharField(blank=True, max_length=100)),
                ('standard_legality', models.CharField(blank=True, max_length=100)),
                ('expanded_legality', models.CharField(blank=True, max_length=100)),
                ('regulation_mark', models.CharField(blank=True, max_length=100)),
                ('small_image', models.URLField(blank=True)),
                ('large_image', models.URLField(blank=True)),
                ('tcgplayer_url', models.URLField(blank=True)),
                ('tcgplayer_updated_at', models.DateField(blank=True)),
                ('tcgplayer_prices', models.JSONField()),
                ('cardmarket_url', models.URLField(blank=True)),
                ('cardmarket_updated_at', models.DateField(blank=True)),
                ('cardmarket_prices', models.JSONField()),
                ('in_collection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('printed_total', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('unlimited_legality', models.CharField(blank=True, max_length=100)),
                ('standard_legality', models.CharField(blank=True, max_length=100)),
                ('expanded_legality', models.CharField(blank=True, max_length=100)),
                ('ptcgo_code', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('symbol', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cards', models.ManyToManyField(to='main.card')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_set', to='main.set'),
        ),
    ]
