# Generated by Django 4.2.1 on 2023-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcgplayer',
            name='prices',
        ),
        migrations.AddField(
            model_name='tcgplayer',
            name='holo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tcgplayer',
            name='normal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='cardmarket',
            name='prices',
        ),
        migrations.DeleteModel(
            name='CardMarketPrices',
        ),
        migrations.DeleteModel(
            name='TcgplayerPrices',
        ),
        migrations.AddField(
            model_name='cardmarket',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
