# Generated by Django 4.2.1 on 2023-07-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ancient_trait',
        ),
        migrations.AddField(
            model_name='card',
            name='ancient_trait',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.ancienttrait'),
            preserve_default=False,
        ),
    ]
