# Generated by Django 4.2.1 on 2023-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_card_abilities_alter_card_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='attacks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardmarket_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='national_pokedex_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='resistances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='retreat_cost',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
