# Generated by Django 4.2.1 on 2023-07-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tcgplayer_prices_tcgplayer_holo_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilities',
            options={},
        ),
    ]
