# Generated by Django 4.2.1 on 2023-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_card_abilities_alter_card_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='expanded_legality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='set',
            name='standard_legality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='set',
            name='unlimited_legality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
