# Generated by Django 4.2.1 on 2023-07-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_abilities_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardset',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
