# Generated by Django 4.2.1 on 2023-07-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_card_ancient_trait_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attacks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
