# Generated by Django 4.2.1 on 2023-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_card_attacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
