# Generated by Django 4.2.1 on 2023-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_card_weaknesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='resistances',
            field=models.TextField(blank=True, null=True),
        ),
    ]
