# Generated by Django 4.2.1 on 2023-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_card_resistances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardmarket_prices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer_prices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
