# Generated by Django 4.2.1 on 2023-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_card_cardmarket_prices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['id']},
        ),
    ]
