# Generated by Django 4.2.1 on 2023-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_card_options_alter_set_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
