# Generated by Django 4.2.3 on 2023-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_collection_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='attacks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardmarket_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='resistances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
