# Generated by Django 4.2.3 on 2023-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_card_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
