# Generated by Django 4.2.3 on 2023-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_attacks_card_attack_one_card_attack_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='weaknesses',
            new_name='weaknesses_one',
        ),
        migrations.AddField(
            model_name='card',
            name='weaknesses_three',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='weaknesses_two',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
