# Generated by Django 4.2.3 on 2023-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_weaknesses_card_weaknesses_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='resistances',
            new_name='resistances_one',
        ),
        migrations.AddField(
            model_name='card',
            name='resistances_three',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='resistances_two',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
