# Generated by Django 4.2.3 on 2023-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_resistances_card_resistances_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tcgplayer_prices',
        ),
        migrations.AddField(
            model_name='card',
            name='tcgplayer_prices_holo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tcgplayer_prices_normal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
