# Generated by Django 4.2.3 on 2023-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_card_cardmarket_prices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='abilities',
        ),
        migrations.AddField(
            model_name='card',
            name='ability_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
