# Generated by Django 4.2.3 on 2023-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_card_abilities_card_ability_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='evolves_to',
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
