# Generated by Django 4.2.3 on 2023-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_ability_type_card_type_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type_one',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type_two',
        ),
    ]
